# Generated by Django 4.1.3 on 2022-11-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_pactientaccount_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='pactientaccount',
            name='gender',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
